"""
Django settings for the project.

Generated by 'django-admin startproject' using Django.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from decouple import Csv, config
from dj_database_url import parse as db_url
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _

from apps.shop.enums import PaymentGateway

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# General

DEBUG = config("DEBUG", default=False, cast=bool)
SECRET_KEY = config("SECRET_KEY")

# Hosts

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv())

# Application definition

DJANGO_APPS = [
    "pyaa.apps.AppAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.humanize",
    "django.contrib.sessions",
    "django.contrib.sitemaps",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.forms",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "compressor",
    "sass_processor",
    "django_admin_extras",
    "django_cleanup.apps.CleanupConfig",
    "tinymce",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",
    "widget_tweaks",
    "cache_cleaner",
    "django_recaptcha",
    "rangefilter",
    "django_admin_listfilter_dropdown",
    "django_q",
    "django_translation_flags",
    "localflavor",
]

PROJECT_APPS = [
    "apps.backup",
    "apps.blog.apps.BlogAppConfig",
    "apps.site.apps.SiteAppConfig",
    "apps.user.apps.UserAppConfig",
    "apps.web.apps.WebAppConfig",
    "apps.report.apps.ReportAppConfig",
    "apps.customer.apps.CustomerAppConfig",
    "apps.system_log.apps.SystemLogAppConfig",
    "apps.language.apps.LanguageAppConfig",
    "apps.content.apps.ContentAppConfig",
    "apps.gallery.apps.GalleryAppConfig",
    "apps.shop.apps.ShopAppConfig",
    "apps.banner.apps.BannerAppConfig",
    "apps.newsletter.apps.NewsletterAppConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + PROJECT_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "pyaa.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "pyaa.context_processors.site_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "pyaa.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": config(
        "DATABASE_URL",
        default="sqlite:///" + os.path.join(BASE_DIR, "db", "db.sqlite3"),
        cast=db_url,
    )
}

# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
# https://www.honeybadger.io/blog/caching-in-django/

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ("en", _("language.en")),
    ("pt-br", _("language.pt-br")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

DEFAULT_TIME_ZONE = "America/Sao_Paulo"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [
    BASE_DIR / "apps" / "web" / "static",
]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "compressor.finders.CompressorFinder",
    "sass_processor.finders.CssFinder",
]

SASS_PROCESSOR_INCLUDE_DIRS = []
SASS_PROCESSOR_AUTO_INCLUDE = False
SASS_PROCESSOR_ROOT = BASE_DIR / "apps" / "web" / "static"

# Compress static files

COMPRESS_ROOT = BASE_DIR / "static"
COMPRESS_ENABLED = True
COMPRESS_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)

# Messages

MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Rest framework

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.DjangoModelPermissions",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "1/second", "user": None},
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_RENDERER_CLASSES": (
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
    ),
}

# Spectacular

SPECTACULAR_SETTINGS = {
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# Simple JWT

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365 * 999),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365 * 999),
}

# Storage

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "s3": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": config("AWS_ACCESS_KEY_ID", default=None),
            "secret_key": config("AWS_SECRET_ACCESS_KEY", default=None),
            "bucket_name": config("AWS_S3_BUCKET_NAME", default=None),
            "region_name": config("AWS_REGION", default=None),
            "default_acl": "public-read",
            "querystring_auth": False,
        },
    },
}

# Media

MEDIA_URL = config("APP_MEDIA_URL", default="/media/")
MEDIA_ROOT = BASE_DIR / "media"

# Editor

UPLOAD_PATH = "uploads"

TINYMCE_DEFAULT_CONFIG = {
    "height": "400px",
    "width": "100%",
    "menubar": True,
    "plugins": "advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime media table code help wordcount",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent | numlist bullist checklist | forecolor backcolor casechange permanentpen formatpainter removeformat | pagebreak | insertfile image media pageembed template link anchor codesample | charmap emoticons | fullscreen preview save print | a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "images_upload_url": "/upload-image/",
    "relative_urls": False,
    "remove_script_host": False,
    "convert_urls": True,
    "valid_elements": "*[*]",
}

# CORS

CORS_ALLOW_ALL_ORIGINS = True

# Site

SITE_ID = 1

# Authentication

AUTHENTICATION_BACKENDS = ("apps.user.backends.MultiFieldModelBackend",)

LOGIN_REDIRECT_URL = "home"

AUTH_USER_MODEL = "user.User"

LOGIN_URL = "account_login"

# Email

EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="webmaster@localhost")
DEFAULT_TO_EMAIL = config("DEFAULT_TO_EMAIL", default="webmaster@localhost")

# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}

# Customer

CUSTOMER_SIGNUP_PLAN = 0
CUSTOMER_ACTIVATION_REQUIRED = False

# Stripe

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")

# Recaptcha

RECAPTCHA_PUBLIC_KEY = config("RECAPTCHA_PUBLIC_KEY", default="")
RECAPTCHA_PRIVATE_KEY = config("RECAPTCHA_PRIVATE_KEY", default="")

# Django Q

Q_CLUSTER = {
    "name": "djangoq",  # name of the cluster for identification
    "workers": 4,  # number of worker processes handling tasks (reduce if using a low-resource server)
    "recycle": 500,  # number of tasks a worker processes before being replaced (helps prevent memory leaks)
    "timeout": 600,  # maximum execution time (in seconds) for a task before being terminated
    "retry": 600,  # delay (in seconds) before retrying a failed task
    "max_attempts": 2,  # maximum number of retry attempts for failed tasks
    "bulk": 20,  # number of tasks fetched from the database at once (reduces db queries)
    "orm": "default",  # defines the orm for job persistence (default database in django settings)
}

# Gateway

GATEWAY_FOR_PRODUCT_PURCHASE = PaymentGateway.STRIPE

# Banner
BANNER_ACCESS_INTERVAL = 86400  # 1 day in seconds

# System Log

SYSTEM_LOG_API_ENABLED = True
SYSTEM_LOG_WEBHOOK_ENABLED = False
