# Generated by Django 5.2.5 on 2025-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="is published"),
        ),
    ]
