# Generated by Django 5.2.5 on 2025-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="shop.product",
                verbose_name="products",
            ),
        ),
    ]
