# Generated by Django 5.2.5 on 2025-09-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short description for SEO.",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
